# Generated by Django 2.1.7 on 2019-04-17 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0003_comment_poll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linde_id', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'ชาย'), ('F', 'หญิง'), ('X', 'อื่นๆ')], max_length=1)),
                ('birthdate', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
