# Generated by Django 2.1.7 on 2019-04-17 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='linde_id',
            new_name='line_id',
        ),
    ]
